### ISSUE TITLE
Handling of broken (music) files

### ISSUE THREAD

**Issue by aanno** [kawaiiDango/youtube-music-upload-sync#2]
Hello kawaiiDango,

I tried your script and found it very promising. However, I've got a real _big_ music collection and some files in it are broken (wrong format, disk errors, empty, etc.). Hence when I try your script, this is what happens:

```python
youtube-music-upload-sync$ python3 sync.py -rc
Fetching list of uploaded songs. For a lot of songs, this may take a long time...
Reading tags from local files...
Traceback (most recent call last):
  File "sync.py", line 201, in <module>
    localTracks = getAllLocalTracks()
  File "sync.py", line 73, in getAllLocalTracks
    metadata = mutagen.File(filePath)
  File "/usr/lib/python3/dist-packages/mutagen/_util.py", line 168, in wrapper_func
    return func(h, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/mutagen/_file.py", line 301, in File
    return Kind(fileobj, filename=filething.filename)
  File "/usr/lib/python3/dist-packages/mutagen/_file.py", line 48, in __init__
    self.load(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/mutagen/_util.py", line 189, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/mutagen/_util.py", line 160, in wrapper
    return func(self, h, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/mutagen/flac.py", line 796, in load
    self.__check_header(fileobj, filething.name)
  File "/usr/lib/python3/dist-packages/mutagen/flac.py", line 909, in __check_header
    header = fileobj.read(4)
  File "/usr/lib/python3/dist-packages/mutagen/flac.py", line 69, in read
    raise error("file said %d bytes, read %d bytes" % (
mutagen.flac.error: file said 4 bytes, read 0 bytes
```

For me it looks like that the error handling when looping through the collection needs some improvement: It should ignore unreadable files, print a warning, and then continue with reading the next file.

Kind regards,

aanno

**Comment by kawaiiDango** [comment]
https://github.com/kawaiiDango/youtube-music-upload-sync/commit/d31751def4c8c09f9c0c6ff37ea8aff73052c925
